targets:
  $default:
    builders:
      freezed:
        enabled: true
        options:
          # Generate copyWith method
          copyWith: true
          # Generate toJson method
          toJson: true
          # Generate fromJson factory
          fromJson: true
          # Generate union types
          union: none
      json_serializable:
        enabled: true
        options:
          # Options for json_serializable
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          ignore_unannotated: false
          include_if_null: true
